


all: ascii dado generate ordena pause primos

pause:
	gcc pause.c -o pause

ascii:
	gcc ascii.c -o ascii

dado:
	gcc dado.c -o dado

primos:
	gcc primos.c -o primos

series:
	gcc series.c -o series

generate:
	gcc generate.c -o generate

ordena:
	gcc ordena.c -o ordena -lrt

clean:
	rm -f pause ascii dado primos series generate ordena 
